### ISSUE TITLE
Make `expectedOutputs: path` a template string

### ISSUE THREAD

**Issue by adamkewley** [adamkewley/jobson#10]
Currently, this won't work:

```yaml
expectedOutputs:
- id: ${request.id}
  path: ${request.id}
```
Because `path` is assumed to be a static string rather than a template string. Perhaps assuming all strings in `execution` and `expectedOutputs` are template strings would increase flexibility
