### ISSUE TITLE
variable dependencies

### ISSUE THREAD

**Issue by mtazzari** [adamkewley/jobson#42]
I cannot find a way to write a spec that has variable dependencies, i.e. dependencies that can be determined at the request submission time or at runtime.
Example: I have a script (`script.py`) that I want to apply to a different file each time (let it be a table `table_source_name.txt` where `source_name` is the name of the astronomical source).
I have written this spec but it doesn't work, I guess it's because the ${inputs.source_name} doesn't get executed in the `application/dependencies` but only in the `application/arguments`. Jobson gives indeed fatal error that cannot find the file `/my/dir/tables/table_${inputs.source_name}.txt`.

```
name: My first spec

description: >

  A demo job spec generated when creating a new Jobson deployment. Try it out!


expectedInputs:

- id: source_name
  type: string
  name: Source name
  description: Name of the astronomical source

execution:

  application: python
  arguments:
  - script.py
  - -v


  dependencies:
  - source: /my/dir/tables/table_${inputs.source_name}.txt
    target: table.txt
  - source: /my/dir/script.py
    target: script.py

expectedOutputs:
[...]
```

How can this be implemented in jobson?
A solution would be including the table copy code inside `script.py` but I would rather use jobson to move dependencies.
